### ISSUE TITLE
Payment schedule for multiple debts

### ISSUE THREAD

**Issue by alberto56** [alberto56/hatch-ahora#18]

**Comment by alberto56** [comment]
Repayment schedule, and target payment date, for multiple debt sources.

Let's say we have two debts:

    - name: debt 1
      amount: 1000
      rate: 12
      monthly minimum: 50
    - name: debt 2
      amount: 2000
      rate: 29.99
      monthly minimum: 10

We need to make sure that we can figure out the best payment schdule for these.

We can use existing code:

    ahora()->debtCalculator()->calculate(2000, 29.99, 450);
    ahora()->debtCalculator()->calculate(1000, 12, 50);
    ahora()->debtCalculator()->calculate(837.58, 12, 152.58);
    ahora()->debtCalculator()->calculate(693.38, 12, 500);

Based on the output of the above, we can manually come up with an optimal payment setup to pay the least amount of interest:

For example if we pay 500 a month, the best payment schedule is to pay debt 2 (the one with the highest interest) first:

| MONTH      | DEBT 1  | DEBT 2 | Payment to 1 | Payment to 2 | Total payment |
|------------|---------|--------|--------------|--------------|---------------|
| 0          | 1000    | 2000   | 50           | 450          | 500           |
| 1          | 960     | 1599.98| 50           | 450          | 500           |
| 2          | 919.60  | 1189.97| 50           | 450          | 500           |
| 3          | 878.8   | 769.71 | 50           | 450          | 500           |
| 4          | 837.58  | 338.95 | 152.58       | 347.42       | 500           |
| 5          | 693.38  |        | 500          |              | 500           |
| 6          | 200.31  |        | 202.32       |              | 202.32        |

The above table shows that by paying 500$ a month, we paid a total of 3202.32$ to clear 3000$ of debt, in 7 months. Our total interest paid is 202.32$.

Your task
-----

Your task is to get the multiple-debts-18 branch (shown at https://github.com/alberto56/hatch-ahora/pull/19) which is currently failing, and fix the calculateMultiple() method in ./drupal/custom-modules/my_custom_module/src/DebtCalculator/DebtCalculator.php (and possibly the tests as well) to make sure this passes.

Feel free to make simpler tests for development, add functions and test cases.

As always, avoid functions longer than about 6 lines or with more than one if statement, thanks.

**Comment by suresh-kumara-gist** [comment]
1. In an ideal scenario, how many multiple debts one can give has a input.
2. Suppose user gave 4 debts in that either we have debt which is  'Exceeded max number months'    or   'You cannot repay your loan' how to handle this this scenaio.
3.   From [this doc](https://docs.google.com/spreadsheets/d/1wB-MCf1GwhXaiQIqs_aXcHeEWJerRv_flSbRKuAmxxA/edit?usp=sharing) considering highest interest rate for best repayment is not an ideal solution. Please check and confirm.
4.  Repayment schedule, and target payment date, for multiple debt sources.   ===> Do we need to give target date also ?
5. minimal monthly:   50   -   do we need to consider this minimal monthly ?   In debt calculation we have repayment, where or how do we need to consider minimal monthly. 

### My approach 
7. If all input debts amount is same and rate of interest is different then highest interest rate debt takes priority.
 If all input debts amount is different interest is same then highest amount debt takes priority.
 if both are different then calculate total interest for all and sort by highest interest debt.

**Comment by alberto56** [comment]
> In an ideal scenario, how many multiple debts one can give has a input.

There should be no limit

> Suppose user gave 4 debts in that either we have debt which is 'Exceeded max number months' or 'You cannot repay your loan' how to handle this this scenaio.

Ideally if that happens, please return the message "You cannot repay your loan", and then in the months, you can still show the progress of each debt, but in the last month of max_month, there will still be debt. The goal is to use this to show the progression of total debt over time, even if the debt is not fully paid in that period of time. If you don't have time to do this, please open a follow-up ticket for that, and just return "You cannot repay your loan" here.

> From this doc considering highest interest rate for best repayment is not an ideal solution. Please check and confirm.

In my opinion it's always best to pay off the highest-interest debt first. Please give a specific example where it's not the ideal solution, but that can be in a separate ticket just to keep things simple here.

> Repayment schedule, and target payment date, for multiple debt sources. ===> Do we need to give target date also ?

No, that was my mistake. It will be in another ticket.

> If all input debts amount is same and rate of interest is different then highest interest rate debt takes priority.

OK.

> If all input debts amount is different interest is same then highest amount debt takes priority.

In my opinion this makes no difference: if you have, say 2 debts ($1 and $10) at 10% each, there is no reason to pay the $10 debt first. The entire $11 is accruing at the same rate, so it's like one big bucket of debts. In fact, I would personally do the opposite: because it makes no monetary difference, then why not pay the smallest debt off first, to make it easier (not cheaper though) to manage. Currently I'm fine with any approach though.

> if both are different then calculate total interest for all and sort by highest interest debt.

OK. Again, I would ignore the amount and simply sort by interest rate.

### From Messenger

> Like whether only highest interest rate we need consider or any other possibilities.

No, just the interest rate. We can always make this better in other tickets. Let's keep it simple here.

**Comment by suresh-kumara-gist** [comment]
@alberto56 for the reply. I will consider highest interest for the repayment for this ticket to make it simple.
