### ISSUE TITLE
Single Sign On with Google account

### ISSUE THREAD

**Issue by alberto56** [alberto56/hatch-ahora#8]

**Comment by alberto56** [comment]
* Reenable allowing anonymous users to create an account (this might be temporary just to make sure this issue works)
* New user should be able to create an account using their Google and Facebook account
* Authenticated user who already has an account should be able to link their Google and Facebook account to their account
* Please do this on the `oneclick` branch, currently identical to master

For your tests I have set up the project at https://ahora-stage.dcycleproject.org **and should be available later toady**

This is on a temporary server at 104.236.70.29 and it uses the "oneclick" branch.

**Please paste or send me your SSH public key so I can put it on the server, allowing you to update the code it yourself**

When you push new code to the "oneclick" branch uou will need to update the server using the following command:

ssh root@104.236.70.29 "cd ~/hatch-ahora && git pull origin oneclick && scripts/deploy.sh"

**Comment by alberto56** [comment]
https://ahora-stage2.dcycleproject.org works now.

Waiting on @suresh-kumara-gist 's public sssh key

**Comment by suresh-kumara-gist** [comment]
I have tried https://www.drupal.org/project/varbase_auth  By directly installing on  the server instance. 

https://ahora-stage2.dcycleproject.org/admin/config/social-api/social-auth/google   the redirection url generated for google is http instead of https. so we are getting error as 

Error 400: redirect_uri_mismatch
The redirect URI in the request, http://ahora-stage2.dcycleproject.org/user/login/google/callback, does not match the ones authorized for the OAuth client. To update the authorized redirect URIs, visit: https://console.developers.google.com/apis/credentials/oauthclient/${your_client_id}?project=${your_project_number}


facebook login configured here  https://ahora-stage2.dcycleproject.org/admin/config/social-api/social-auth/facebook

**Comment by alberto56** [comment]
Hi @suresh-kumara-gist thanks, I have set up a deploy key on the server and put all your work on a new branch called social.

You can now pull it locally, work locally, push it back to "social", and deploy on the server like this. Please confirm it works:

ssh root@104.236.70.29 "cd hatch-ahora && ssh-agent bash -c 'ssh-add /root/.ssh/id_ed25519; git pull origin social' && ./scripts/deploy.sh"

Please confirm this works!

For now I am getting this with facebook:

<img width="588" alt="Screen Shot 2021-04-05 at 8 04 02 AM" src="https://user-images.githubusercontent.com/808265/113572074-8963ca80-95e5-11eb-8af9-27fb8ca26467.png">


And this with Google:

<img width="486" alt="Screen Shot 2021-04-05 at 8 04 08 AM" src="https://user-images.githubusercontent.com/808265/113572082-8e287e80-95e5-11eb-88c8-35b47e76c09d.png">

This might have to do with the reverse proxy.

**Comment by alberto56** [comment]
Can you please continue working on the stage site, set up a working version with a dummy "app" on your facebook/google account, and document step-by-step the procedure at the end of the README.md file within the branch, so we can set it up on production? Thanks.

**Comment by alberto56** [comment]
I noticed you installed https://www.drupal.org/project/reverse_proxy_header, but you did not add 

    $settings['reverse_proxy_header'] = 'HTTP_X_FORWARDED_FOR_CUSTOM_HEADER';

Also, in the local settings you added:

    $_SERVER['HTTPS'] = 'on';
    $_SERVER['SERVER_PORT'] = 443;

Those only pertain to stage development, that is: we should not have them during local development. Therefore, please note the existence of a new file called ./drupal/settings/local-settings/unversioned.example.php on the social branch. 

That is an example file and not used; however if we make a file called ./drupal/settings/local-settings/unversioned.php, it will not be under version control, but still be loaded.

Therefore, each environment can have their own ./drupal/settings/local-settings/unversioned.php file.

You can see and edit the one on the stage server at:

    $ ssh root@104.236.70.29 "cat hatch-ahora/drupal/settings/local-settings/unversioned.php"
    <?php

    $_SERVER['HTTPS'] = 'on';
    $_SERVER['SERVER_PORT'] = 443;
    $settings['reverse_proxy_header'] = 'HTTP_X_FORWARDED_FOR_CUSTOM_HEADER';

Note that "$settings['reverse_proxy_header'] = 'HTTP_X_FORWARDED_FOR_CUSTOM_HEADER';" does not seem to fix the problem we're having.

Please continue investigating that problem, open support tickets, other issues with the modules you're using, as well as question(s) on http://drupal.stackexchange.com, and reference them here.

**Comment by suresh-kumara-gist** [comment]
ssh root@104.236.70.29 "cd hatch-ahora && ssh-agent bash -c 'ssh-add /root/.ssh/id_ed25519; git pull origin social' && ./scripts/deploy.sh"

I have verified. This is working.

**Comment by suresh-kumara-gist** [comment]
> I was trying to fix google social auth default url (http issue), So I have added reverse proxy in local. I have yet to confirm whether it is required or not. 

> I will tried to use  unversioned.php file in future.

> [https://www.drupal.org/project/social_auth_google/issues/3207114](url) I have raised a ticket here.

> I have verified in http://simplytest.me/  . there social auth google is generating https url.

**Comment by alberto56** [comment]
This article is useful: https://medium.com/@lmakarov/drupal-8-and-reverse-proxies-the-base-url-drama-c5553cbc9a3e

**Comment by alberto56** [comment]
I have updated https://www.drupal.org/project/social_auth_google/issues/3207114

**Comment by alberto56** [comment]
See also https://drupal.stackexchange.com/questions/302378/drupal-and-reverse-proxy-how-to-make-drupal-aware-that-its-protocol-is-https

**Comment by alberto56** [comment]
Your issue at https://www.drupal.org/project/social_auth_google/issues/3207114 is now marked as fixed. Please let me know if you have further problems with this.
